tweets = {
"1a": "Every chain claiming Franklin Templeton's agent thesis proves nobody's built it yet.",
"1b": "$1.79T AUM firm calls AI agents blockchain's killer use case. x402 volume so far: $15M.",
"2a": "Franklin Templeton just called agentic AI blockchain's killer use case. Within 48 hours, five different chain communities all said the same thing: that's us.",
"2b": "The fight over which chain wins agentic commerce misses the actual claim in the report: credit cards can't clear a $0.001 payment. That's a settlement problem, not a branding one.",
"3a": "A $1.79T asset manager says AI agents transacting is blockchain's killer use case. In two days, Sui, Solana, and BNB accounts claimed it as their own win. None quoted the real number: x402 has moved $15M since May. The thesis is real. The victory lap isn't.",
"3b": "Sandy Kaul's report doesn't say which chain wins agentic commerce. It says credit card rails can't clear a $0.001 micropayment, so agents paying agents need something else. Every L1 community read that as their own name being called. That's not analysis, it's projection.",
"4a": "Franklin Templeton's report is being read as a chain-selection story: Sui, Solana, Aptos, BNB all got name-checked, so all four communities claimed the win. But the actual argument is narrower and more useful: legacy rails can't clear a $0.001-per-compute-second payment, so agent-to-agent commerce needs settlement infrastructure that doesn't exist yet at scale. x402 has processed 109M+ transactions since May, an impressive count against tiny dollar volume, $15M, versus a $3-5T 2030 projection. The gap between those two numbers is the actual story, and it's not about which chain wins.",
"4b": "Everyone arguing about which L1 wins agentic commerce is skipping the harder problem the report actually points at. A rail that clears $0.001 payments is necessary but not sufficient, you still need a way for two agents that have never met to trust the outcome of a transaction. That's not a throughput question, it's a verification question. Nobody's chain-maxi thread mentions it because it's not a chain feature. It's a missing layer, and most of the projected $3-5T depends on someone building it before agents can actually transact unsupervised.",
"5a": "A $1.79T asset manager just said AI agents transacting is blockchain's killer use case, projected at $3-5T by 2030. Within 48 hours every L1 community had quote-tweeted it as their own validation. Here's what the report actually says, and what it leaves out.",
"5b": "x402 has processed 109M+ agentic transactions since May. Total volume: $15M. The report projecting a $3-5T agentic-commerce market by 2030 is being read as chain marketing. It's actually a roadmap for what's still missing. Thread.",
}
for k, v in tweets.items():
    print(k, len(v))
